name: CI
on:
  pull_request:
  workflow_dispatch:
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
      fail-fast: false
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v2
      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.11.0-dev.4002+7dd1cf26f
      - run: |
          zig build test -Dfetch -Dis_ci
          zig build all -Dis_ci
        shell: bash
      - uses: actions/upload-artifact@v2
        with:
          name: ziget ${{ matrix.os }}
          path: zig-out/bin/*
